// Generated by dts-bundle v0.7.3

declare module 'ue-elems' {
    export * from 'ue-elems/elem/index';
}

declare module 'ue-elems/elem/index' {
    export { UeText } from 'ue-elems/elem/ue-text';
    export { UeButton } from 'ue-elems/elem/ue-button';
    export { UeSlider } from 'ue-elems/elem/ue-slider';
    export { UeIcon } from 'ue-elems/elem/ue-icon';
}

declare module 'ue-elems/elem/ue-text' {
    export const UeText: import("hybrids").HybridElement<any>;
}

declare module 'ue-elems/elem/ue-button' {
    export const UeButton: import("hybrids").HybridElement<any>;
}

declare module 'ue-elems/elem/ue-slider' {
    export const UeSlider: import("hybrids").HybridElement<any>;
}

declare module 'ue-elems/elem/ue-icon' {
    export const UeIcon: import("hybrids").HybridElement<any>;
}

